require("prototypes.entity._entity")
require("prototypes.item._item")
require("prototypes.recipe._recipe")
require("prototypes.technology._technology")

require("prototypes.planet.installation-map-gen")
require("prototypes.planet.map-gen")
require("prototypes.planet.planet")

require("prototypes.custom-input")
require("prototypes.event")
require("prototypes.shortcuts")
require("prototypes.sprits")
require("prototypes.tile")
require("prototypes.tips-and-tricks")