return {
  panel_description_1 = "BAD 시스템에 설계도면을 만들고 추가하는 방법:\n\n1단계: 콘크리트 바닥 설계도면을 복사합니다. 이 설계도면은 BAD 상자 안에 있는 설계도면 책자에 있습니다.\n\n2단계: 복사한 설계도면의 이름을 원하는 이름으로 변경합니다.",
  panel_description_1_1 = "3단계: 새 설계도면에 원하는 내용을 포함시킵니다. 이 때 shift 키를 눌러 콘크리트 바닥 타일을 포함하도록 해야 합니다.\n\n4단계: 새 설계도면을 설계도면 책자 내의 원하는 위치에 넣습니다.\n\n5단계: 원하는 값과 설계도면 책자에 있는 설계도면의 위치를 ​​상수 조합기에 입력합니다.",
  panel_description_2 = "팁: 시스템을 켜둔 상태에서 일시 정지 버튼을 활성화하면 UPS 소모량이 줄어듭니다. 또한, 이는 설계도면을 그리거나 업데이트할 때 권장되는 방법입니다.\n\n팁: BAD 상자의 중심을 찾으려면 시스템을 끄고 \"BAD 상자 영역 표시기\"를 사용하여 건설 영역을 확인하세요.",
  panel_description_2_1 = "팁: 새 설계도면을 그리거나 업데이트하기 전에 일시정지 신호를 켜는 것을 잊지 마세요.\n\n일시정지 버튼이 활성화되면 빨간색 표시등이 켜집니다.\n\n\"테이블을 초기화\"하려면 일시정지 버튼을 껐다가 다시 켜세요.",
  panel_stage = "스테이지 표시기는 현재 어떤 스테이지가 활성화되어 있는지 알려줍니다.",
  panel_request = "요청 표시기는 요청이 어느 스테이지에서 활성화 되었는지 알려줍니다.",
  
  combinator_turn_on = "녹색 = 켬 신호",
  combinator_parameter = "좌표 및 크기 매개변수\n\n이 조합기를 끄기 전에 BAD 상자에 연결된 신호 케이블을 잘라주세요.\n\n팁: BAD 상자 영역의 중심 좌표를 찾으려면 \"BAD 상자 영역 표시기\"를 사용하세요.",
  combinator_deconstruction = "해체 신호",
  combinator_construction = "건설 신호",
  combinator_stepper = "스테퍼",
  combinator_signal_converter = "신호 변환기",
  combinator_signal_retarder = "신호 지연기",
  combinator_signal_sorter = "이 조합기는 시스템에 가장 높은 우선순위를 가진 아이템부터 시작하여 어떤 설계도면을 선택해야 하는지 알려줍니다.",
  combinator_pause = "일시정지 신호\n\n설계도면을 새로 그리거나 업데이트 하려면 이 신호를 활성화하세요.",
      
  combinator_signal_filter_1 ="스테이지 1 신호 필터",
  combinator_signal_filter_2 ="스테이지 2 신호 필터",
  combinator_id_box_1 ="ID 상자 - 스테이지 1\n\n아이템 신호의 값을 통해 BAD 상자의 설계도면 책자에서 어떤 설계도면을 선택할지 결정합니다. 이 값이 작을수록(책자에서 위에 있을수록) 우선순위가 높습니다.",
  combinator_id_box_2 ="ID 상자 - 스테이지 2\n\n아이템 신호의 값을 통해 BAD 상자의 설계도면 책자에서 어떤 설계도면을 선택할지 결정합니다. 이 값이 작을수록(책자에서 위에 있을수록) 우선순위가 높습니다.",
  combinator_signal_gate_1 = "스테이지 1 게이트",
  combinator_signal_gate_2 = "스테이지 2 게이트",
  combinator_latch_negative = "반전 신호 버전\n\n아이템 신호 래치",
  combinator_latch_positive = "일반 신호 버전\n\n아이템 신호 래치",
  
  combinator_gate_negative_high="반전 신호 버전:\n\n고점 신호 게이트 : 재고량이 지정된 양보다 많으면 해당 아이템의 신호를 출력합니다.",
  combinator_gate_negative_low="반전 신호 버전:\n\n저점 신호 게이트 : 재고량이 지정된 양보다 적으면 해당 아이템의 신호를 출력합니다.",
  combinator_gate_positive_high="일반 신호 버전:\n\n고점 신호 게이트 : 재고량이 지정된 양보다 많으면 해당 아이템의 신호를 출력합니다.",
  combinator_gate_positive_low="일반 신호 버전:\n\n저점 신호 게이트 : 재고량이 지정된 양보다 적으면 해당 아이템의 신호를 출력합니다.",
  
  combinator_box_negative_high="반전 신호 버전:\n\n상한선 설정\n\n아이템의 재고량이 여기에 설정된 수량을 초과하면 해당 아이템의 신호가 켜집니다.",
  combinator_box_negative_low="반전 신호 버전:\n\n하한선 설정\n\n아이템의 재고량이 여기에 설정된 수량보다 줄어들면 해당 아이템의 신호가 꺼집니다.",
  combinator_box_positive_high="일반 신호 버전:\n\n상한선 설정\n\n아이템의 재고량이 여기에 설정된 수량을 초과하면 해당 아이템의 신호가 꺼집니다.",
  combinator_box_positive_low="일반 신호 버전:\n\n하한선 설정\n\n아이템의 재고량이 여기에 설정된 수량보다 줄어들면 해당 아이템의 신호가 켜집니다.",
}