local __PATH__ = "prototypes.item."

require(__PATH__.."dysprosium-data-card")
require(__PATH__.."dysprosium-exoskeleton-equipment")
require(__PATH__.."dysprosium-powder")
require(__PATH__.."enable-entity")
require(__PATH__.."erbium-data-card")
require(__PATH__.."erbium-oxide")
require(__PATH__.."erbium-powder")
require(__PATH__.."hydrophilic-rare-earth-powder")
require(__PATH__.."hydrophobic-rare-earth-powder")
require(__PATH__.."lava-data-card")
require(__PATH__.."neodymium-data-card")
require(__PATH__.."neodymium-oxide")
require(__PATH__.."neodymium-permanent-magnet")
require(__PATH__.."neodymium-powder")
require(__PATH__.."rare-earth-data-card")
require(__PATH__.."rare-earth-powder")
require(__PATH__.."samarium-data-card")
require(__PATH__.."samarium-powder")
require(__PATH__.."samarium")
require(__PATH__.."tungsten-gear-wheel")
require(__PATH__.."tungsten-stick")