require("prototypes.entity.npc.lorax");
require("prototypes.entity.npc.network-terminal");
require("prototypes.entity.npc.power-converter");
require("prototypes.entity.advanced-rocket-silo");
require("prototypes.entity.cargo-elevator");
require("prototypes.entity.cargo-landing-pad");
require("prototypes.entity.chemical-filter");
require("prototypes.entity.chemical-tank");
require("prototypes.entity.common");
require("prototypes.entity.core-roboport");
require("prototypes.entity.deep-oil-pumpjack");
require("prototypes.entity.erbium-beacon");
require("prototypes.entity.fluid-elevator");
require("prototypes.entity.huge-heat-exchanger")
require("prototypes.entity.linox-supercomputer")
require("prototypes.entity.mantle-extractor")
require("prototypes.entity.neodymium-permanent-magnet-generator")
require("prototypes.entity.outlet")
require("prototypes.entity.sintering-machine")
require("prototypes.entity.sulfuric-acid-pumpjack")
require("prototypes.entity.turbo-pump");